matrix:
  include:
    # Linux build
    - language: node_js
      node_js:
        - 12.10.0
      sudo: true
      before_install: 
        - sudo apt update
        - sudo apt install rpm fakeroot
      before_script: 
        - npm install --global electron-forge
        - npm install
      script: electron-forge make
    # Windows build
    - language: node_js
      os: windows
      node_js:
        - 12.10.0
      before_script: 
        - npm install --global electron-forge
        - npm install
      script: electron-forge make
    #  script: ./js-checks.bash
    ## macOS build
    #- language: node_js
    #  os: osx
    #  node_js:
    #    - 12.10.0
    #  sudo: true
    #  script: ./js-checks.bash
