matrix:
  include:
    # Linux build (Ubuntu default)
    - language: node_js
      node_js:
        - 14.5.0
      sudo: true
      before_install: 
        - sudo apt update
        - sudo apt install fakeroot
      before_script: 
        - npm install --global electron-forge
        - npm install
      script: electron-forge make
    # Windows build
    - language: node_js
      os: windows
      node_js:
        - 14.5.0
      before_script: 
        - npm install --global electron-forge
        - npm install
        - npm install electron-prebuilt-compile@8.2.0 --save-dev
      script: electron-forge make
    # macOS build
    - language: node_js
      os: osx
      node_js:
        - 14.5.0
      before_script: 
        - npm install --global electron-forge
        - npm install
      script: electron-forge make
